{% set name = "autovizwidget" %}
{% set version = "0.19.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "9fefb05fc274218b8446ebff62c5f2675bbb6f1e8efa41bdfaaebcfd7ff2128c" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    {{ hash_type }}: {{ hash_val }}

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
    host:
        - python >=3.6
        - pip
        - wheel
        - setuptools
    run:
        - python >=3.6
        - plotly >=3
        - ipywidgets >=5.0.0
        - hdijupyterutils >=0.6.0
        - notebook >=4.2
        - pandas >=0.20.1

test:
    imports:
        - autovizwidget
    requires:
        - pip
    commands:
        - pip check

about:
    home: https://github.com/jupyter-incubator/sparkmagic/tree/master/autovizwidget
    license: BSD 3-clause
    license_family: BSD
    license_file: LICENSE.md
    summary: An Auto-Visualization library for pandas dataframes
    doc_url: https://github.com/jupyter-incubator/sparkmagic/blob/master/autovizwidget/README.md
    dev_url: https://github.com/jupyter-incubator/sparkmagic/tree/master/autovizwidget


extra:
  recipe-maintainers:
    - dbast
