{% set name = "autovizwidget" %}
{% set version = "0.18.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "24b9507a02a92adef7e96ee1ee7bfb77b5a7fc46139eb046eef5b9e20eca710b" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    {{ hash_type }}: {{ hash_val }}

build:
    noarch: python
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
    host:
        - python
        - pip
    run:
        - python
        - plotly >=3
        - ipywidgets >=5.0.0
        - hdijupyterutils >=0.6.0
        - notebook >=4.2
        - pandas >=0.20.1

test:
    imports:
        - autovizwidget

about:
    home: https://github.com/jupyter-incubator/sparkmagic/tree/master/autovizwidget
    license: BSD 3-clause
    summary: An Auto-Visualization library for pandas dataframes


extra:
  recipe-maintainers:
    - ""
