{% set name = "autovizwidget" %}
{% set version = "0.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autovizwidget-{{ version }}.tar.gz
  sha256: 5e413362a6800fa32e6549d1d314a167b46dfc4850c4750cc8d8b6a7db486068

build:
  number: 0
  # The downstream sparkmagic dropped support for Python 3.6,
  # see https://github.com/jupyter-incubator/sparkmagic/blob/0.20.0/CHANGELOG.md#updates
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - hdijupyterutils >=0.6
    - ipywidgets >5.0.0
    - notebook >=4.2
    - pandas >=0.20.1
    - plotly >=3

test:
  imports:
    - autovizwidget
    - autovizwidget.plotlygraphs
  commands:
    - pip check || true
  requires:
    - pip

about:
  home: https://github.com/jupyter-incubator/sparkmagic/tree/master/autovizwidget
  summary: 'AutoVizWidget: An Auto-Visualization library for pandas dataframes'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  license_url: https://github.com/jupyter-incubator/sparkmagic/blob/master/autovizwidget/LICENSE.md
  dev_url: https://github.com/jupyter-incubator/sparkmagic/tree/master/autovizwidget

extra:
  recipe-maintainers:
    - dbast
    - devstein