travis:
  secure:
    BINSTAR_TOKEN: g0ukHRHTqswg3lNTFieuN8zDK7G8TJZNUyBGw4a5ErteKnw/HxjzrEMk5Bb3QalJ2ySDFfwgVp3HTUvAHJLoia07uiXI5uVwJcH3Q4wwxiTHwe0J71hg2O2amJdjZNh2x+e9Jn6pmMVZh5lD8+s8dA58oPdtc7V9OKHZehmTamHxt1IBZm///sauS9nVrYq0AcFuJcCv1e1ybdh7GibylK9hlTIwGFaxGBgf1kbEFJejUK5L794x7639jWqS0bwooHMbSSF/gSb+8kotjWb35T2TTOGZ92m93HJGc1j9ljQ499HWyCFXsEZQs/KuybUjotWH/2pRWNwzviV5fTfPt4xJa7YFrJE0OTZEHe0rJTYbNO5QwyPClO8oxvMEf3/OuLojTWlGnp0Xm2f/Y3RMrqTpChib38WmBlO3wXN5/FVXx38NfcdFVBQhL2YOeTdav0nrbnpV+fVMRlJkrsqeSPgHpDtP7XV51FonAXx9mgnbhtUKs63b6XiLIJWa1Z3sCMyRsSC2CkrviFQAR3udFNdmKgD4yedHcwxN5T4oNjLt7pJPvqnsUq5gE/busFv5H3Bc6gLTOi4hS4Xaw2kqwFC2NVu4CnsqDQLkP6/oXgX4U1P7DZZR+/6dVZkOyCbfQWQowW4wpLwuI6ePtJZ2fMFUBjlN83G6DGyNhtjCRGE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
