travis:
  secure:
    BINSTAR_TOKEN: GUUPFBnGpDvSKw25+3/qwCZO9UlAdL2XZEhTJbL2QnGCWogqJJF45MyCfrhiZjQLOvdGGQlaEzg8cd2gw4c4SomHgWAfvT5WfiFnjGh5ArDUm+nll+ccbiUAzu/p7CCEZaD1TZQv1E7Z+PcBw+TaYDgc+5lfoGBPd8C2T9u9vD7KxcpEz7jqJX5vPHY/zsk45l0gVDfX1z4UBRrIxkQP1bXB24IDFnFKaJl8eV4UnwCkVh2DE/Qf8bhCMnNUV80AshXacCPSL7yGHSnqI0l16UvPk7PecQ5byvSE5Vwz1MHvWND+cDeKRLMbrQhFuN+LVuHMcv1ac0xqcc879slInhmdS9JuO4mlP7TcmHzPqtFULqUCTqYtHGlQTPkHe8uFoRTX/ZoH8gIfiLHIVD0rfyaGIEBWhi5H9MZI2l7KtSKy4J8OZ4i619FQidb6WK32mxSKVgPuDFWUKIKv6iHOtC+mKbU1jDuKsVGoHUmH2ygN76I2CLjDwzLvzfKN9HSYl8Yure0y/ClW1Lcg6VCPLwiyR/K1CLKUFZKdbKxePhkMiuF5cjEo8xqTf8zq6n0TY2/gZ+w+sw83XaLnJRnTDlPv2zbZQFEBadIsDsvzf+7fpC+lOYaLMLxV9UDmKwpncXYjMd0ghyth1Ur8et/BrM7otj60kcyVAs621ncAmvA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
